services:
  - type: web
    name: bibliotheque-univ-nz
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sql8.freesqldatabase.com:3306/sql8828189?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: sql8828189
      - key: SPRING_DATASOURCE_PASSWORD
        value: IQIIZqNG33
      - key: JWT_SECRET
        value: bibliothequeUnivNZSecretKey2024XYZ
      - key: SPRING_MAIL_USERNAME
        value: moumounibanao0@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: opct bymi bfta kdea
