services:
  - type: web
    name: bibliotheque-univ-nz
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-3c88a380-banaomoumouni12-43fa.c.aivencloud.com:19836/defaultdb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: AVNS_SzBpCEIp8jT1V0dbPMC
      - key: JWT_SECRET
        value: bibliothequeUnivNZSecretKey2024XYZ
      - key: SPRING_MAIL_USERNAME
        value: moumounibanao0@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: opct bymi bfta kdea
