# Nom de l'application
spring.application.name=bibliotheque-univ

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d83najt7vvec739qc7bg-a/bibliotheque_db_ae09
spring.datasource.username=bibliotheque_db_ae09_user
spring.datasource.password=3c2ycLS93KIUwcss1QLESNJN6kMrt6as
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8081

# JWT
jwt.secret=bibliothequeUnivNZSecretKey2024XYZ
jwt.expiration=86400000
